[[pages]]
path = "streamlit/section_2_typology_teams.py"
name = "2. Typology of teams by country"

[[pages]]
path = "streamlit/section_3_typology_clubs.py"
name = "3. Typology of clubs by country"

[[pages]]
path = "streamlit/section_4_churn_analysis.py"
name = "4. Churn Analysis"

[[pages]]
path = "streamlit/section_5_turnover.py"
name = "5. Turnover Analysis YoY"
